force-app/main/default/objects/Link__mdt/Link__mdt.object-meta.xml
<CustomObject>
    <label>External Link</label>
    <pluralLabel>External Links</pluralLabel>
</CustomObject>

force-app/main/default/objects/Link__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/RelatedLinksController.cls
public class RelatedLinksController {
    @AuraEnabled(Cacheable=true)
    public static List<Link__mdt> fetchLinks() {
        MetadataHolder metadataHolder = MetadataHolder.getInstance();
        return (List<Link__mdt>) metadataHolder.getAll(Link__mdt.getSObjectType());
    }

    @AuraEnabled(Cacheable=true)
    public static String getApiServerUrl() {
        MetadataHolder metadataHolder = MetadataHolder.getInstance();
        Link__mdt linkItem = (Link__mdt) metadataHolder.get(Link__mdt.getSObjectType(), 'API_server');
        return linkItem == null ? null : linkItem.URL__c;
    }
}