force-app/main/default/objects/AppUser__x/AppUser__x.object-meta.xml
<CustomObject>
    <externalDataSource>Heroku_Postgres</externalDataSource>
    <externalName>public$xm_user</externalName>
    <label>AppUser</label>
    <pluralLabel>AppUsers</pluralLabel>
</CustomObject>

force-app/main/default/objects/AppUser__x/fields/Last_Login__c.field-meta.xml
<CustomField>
    <fullName>Last_Login__c</fullName>
    <externalDeveloperName>last_login</externalDeveloperName>
    <label>Last Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <externalDeveloperName>name</externalDeveloperName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalDeveloperName>user_id</externalDeveloperName>
    <label>User Id</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <externalDeveloperName>username</externalDeveloperName>
    <label>Username</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdminService.cls
public inherited sharing class AdminService extends CalloutExecutor {
    private PropertyMapper mapper;

    private AdminService() {
        this.mapper = new AppUserMapper();
    }

    public static AdminService getInstance() {
        return new AdminService();
    }

    public Boolean updateUser(AppUser__x appUser) {
        super.sendRequest(CalloutConstants.ENDPOINT + '/updateUser', 'PUT', appUser);
        return true;
    }

    public Boolean deleteUser(AppUser__x appUser) {
        super.sendRequest(CalloutConstants.ENDPOINT + '/deleteUser', 'DELETE', appUser);
        return true;
    }

    public List<AppUser__x> getUsersOnline() {
        HttpResponse response = super.sendRequest(CalloutConstants.ENDPOINT + '/indicators');
        List<Indicator> indicators = (List<Indicator>) JSON.deserialize(response.getBody(), List<Indicator>.class);
        Set<Integer> activeUserIds = new Set<Integer>();
        for (Indicator indicatorItem : indicators) {
            activeUserIds.add(indicatorItem.id);
        }
        return [
                SELECT Id
                        , Name__c
                        , Username__c
                FROM AppUser__x
                WHERE User_Id__c IN :activeUserIds
                ORDER BY Last_Login__c DESC
                LIMIT 6
        ];
    }

    protected override String serializeBody(Object body) {
        AppUser__x appUser = (AppUser__x) body;
        Object payload = this.mapper.mapProperties(appUser);
        return super.serializeBody(payload);
    }

    private class Indicator {
        public Integer id;
        public Boolean active;
        public String datestamp;

        public Indicator() {
        }
    }
}