force-app/main/default/objects/AppUser__x/AppUser__x.object-meta.xml
<CustomObject>
    <externalDataSource>Heroku_Postgres</externalDataSource>
    <externalName>public$xm_user</externalName>
    <label>AppUser</label>
    <pluralLabel>AppUsers</pluralLabel>
</CustomObject>

force-app/main/default/objects/AppUser__x/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <externalDeveloperName>active</externalDeveloperName>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalDeveloperName>user_id</externalDeveloperName>
    <label>User Id</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <externalDeveloperName>username</externalDeveloperName>
    <label>Username</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AppUserMapper.cls
public without sharing class AppUserMapper implements PropertyMapper {

    private AppUserMapper() {
    }

    public static AppUserMapper getInstance() {
        return new AppUserMapper();
    }

    public Object mapProperties(SObject record) {
        AppUser__x appUser = (AppUser__x) record;
        Map<String, Object> resultMap = new Map<String, Object>{
                'id' => appUser.User_Id__c,
                'username' => appUser.Username__c,
                'active' => appUser.Active__c
        };
        return resultMap;
    }
}