force-app/main/default/objects/AppUser__x/AppUser__x.object-meta.xml
<CustomObject>
    <externalDataSource>Heroku_Postgres</externalDataSource>
    <externalName>public$xm_user</externalName>
    <label>AppUser</label>
    <pluralLabel>AppUsers</pluralLabel>
</CustomObject>

force-app/main/default/objects/AppUser__x/fields/Fullname__c.field-meta.xml
<CustomField>
    <fullName>Fullname__c</fullName>
    <externalDeveloperName>name</externalDeveloperName>
    <label>Fullname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalDeveloperName>user_id</externalDeveloperName>
    <label>User Id</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <externalDeveloperName>username</externalDeveloperName>
    <label>Username</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdminControllerTest.cls
@IsTest
private class AdminControllerTest {
    private final static Integer SC_OK = 200;
    private final static Integer SC_BAD_REQUEST = 400;

    testMethod static void deactivateUser() {
        AppUser__x appUser = composeAppUser();
        Test.setMock(HttpCalloutMock.class, new TestRequest(SC_OK));
        HttpResponse response = (HttpResponse) AdminController.deactivateUser(appUser);
        System.assertEquals(SC_OK, response.getStatusCode());
        Test.setMock(HttpCalloutMock.class, new TestRequest(SC_BAD_REQUEST));
        response = (HttpResponse) AdminController.deactivateUser(appUser);
        System.assertEquals(SC_BAD_REQUEST, response.getStatusCode());
    }

    private static AppUser__x composeAppUser() {
        String userId = '1234';
        AppUser__x appUser = new AppUser__x();
        appUser.ExternalId = userId;
        appUser.User_Id__c = Integer.valueOf(userId);
        appUser.Fullname__c = 'Test App User';
        appUser.Username__c = 'test';
        return appUser;
    }

    public class TestRequest implements HttpCalloutMock {
        private Integer statusCode;

        private TestRequest(Integer statusCode) {
            this.statusCode = statusCode;
        }

        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(this.statusCode);
            return res;
        }
    }
}