force-app/main/default/objects/AppUser__x/AppUser__x.object-meta.xml
<CustomObject>
    <externalDataSource>Heroku_Postgres</externalDataSource>
    <externalName>public$xm_user</externalName>
    <label>AppUser</label>
    <pluralLabel>AppUsers</pluralLabel>
</CustomObject>

force-app/main/default/objects/AppUser__x/fields/Last_Login__c.field-meta.xml
<CustomField>
    <fullName>Last_Login__c</fullName>
    <externalDeveloperName>last_login</externalDeveloperName>
    <label>Last Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <externalDeveloperName>name</externalDeveloperName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AppUser__x/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <externalDeveloperName>username</externalDeveloperName>
    <label>Username</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdminController.cls
public without sharing class AdminController {
    @AuraEnabled
    public static List<AppUser__x> getUsersOnline() {
        try {
            return AdminService.getInstance().getUsersOnline();
//            return [
//                    SELECT Id
//                            , Name__c
//                            , Username__c
//                            , Last_Login__c
//                    FROM AppUser__x
//                    ORDER BY Last_Login__c DESC
//                    LIMIT 6
//            ];
        } catch (Exception ex) {
            System.debug('\n\n ex => ' + ex + '\n');
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void updateUserInfo(AppUser__x appUser) {
        try {
            AppUser__x userToUpdate = appUser.clone(false, true);
            AdminService.getInstance().updateUser(userToUpdate);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteUser(AppUser__x appUser) {
        try {
            AdminService.getInstance().deleteUser(appUser);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}